# Generated by Django 5.0.6 on 2024-06-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('reseñador', 'reseñador'), ('observador', 'observador')], default='observador', max_length=20),
        ),
    ]
