# Generated by Django 5.0.6 on 2024-05-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/'),
        ),
    ]
