# Generated by Django 5.0.6 on 2024-05-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0002_restaurante_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='imagen',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='iimagen',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
