# Generated by Django 5.0.6 on 2024-05-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0003_remove_restaurante_imagen_restaurante_iimagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='iimagen',
            new_name='imagen',
        ),
    ]
