# Generated by Django 5.0.6 on 2024-06-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0005_remove_restaurante_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='telefono',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='horario',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
