# Generated by Django 5.0.6 on 2024-09-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0006_remove_restaurante_email_remove_restaurante_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/'),
        ),
    ]
